# Generated by Django 4.2.2 on 2023-06-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coneccion_ajax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscriptor',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='suscriptor',
            name='nombre',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
